Repository yiisoft/assets, pull requests merged in 2020-06, with the labels that each got.

#26 Fix #25
  docs/asset-converter.md
  src/AssetConverter.php
Labels: type:bug

#27 Enhacements.
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  .gitignore
  README.md
  composer.json
  config/common.php
  config/params.php
  config/test.php
  config/web.php
  infection.json.dist
  tests/AssetBundleTest.php
  tests/AssetManagerTest.php
  tests/AssetPublisherTest.php
  tests/TestCase.php
  tests/stubs/BaseAsset.php
  tests/stubs/CircleAsset.php
  tests/stubs/CircleDependsAsset.php
  tests/stubs/FileOptionsAsset.php
  tests/stubs/JqueryAsset.php
  tests/stubs/Level3Asset.php
  tests/stubs/PositionAsset.php
  tests/stubs/RootAsset.php
  tests/stubs/SimpleAsset.php
  tests/stubs/SourceAsset.php
Labels: status:ready for merge

#28 Fix parameters web config.
  config/web.php
Labels: status:code review

#30 assetConverter doc fix.
  docs/asset-bundles.md
  docs/asset-converter.md
  docs/asset-manager.md
Labels: status:code review, type:docs
